### Creation d'un DataFrame

In [18]:
import pandas as pd
import numpy as np

# ============================
# SOURCE 1 : Ventes par magasin
# ============================
ventes_q1 = pd.DataFrame({
    'produit': ['Laptop', 'Smartphone', 'Tablette', 'Casque', 'Laptop', 
                'Smartphone', 'Tablette', 'Casque', 'Laptop', 'Smartphone'],
    'magasin': ['Paris', 'Paris', 'Paris', 'Paris', 'Lyon', 
                'Lyon', 'Lyon', 'Lyon', 'Marseille', 'Marseille'],
    'quantite': [45, 120, 30, 80, 35, 95, 25, 60, 50, 110],
    'chiffre_affaires': [45000, 60000, 12000, 4000, 35000, 
                         47500, 10000, 3000, 50000, 55000]
})

ventes_q2 = pd.DataFrame({
    'produit': ['Laptop', 'Smartphone', 'Tablette', 'Casque', 'Laptop',
                'Smartphone', 'Tablette', 'Casque', 'Tablette', 'Casque'],
    'magasin': ['Paris', 'Paris', 'Paris', 'Paris', 'Lyon',
                'Lyon', 'Lyon', 'Lyon', 'Marseille', 'Marseille'],
    'quantite': [50, 130, 35, 90, 40, 100, 28, 70, 30, 55],
    'chiffre_affaires': [50000, 65000, 14000, 4500, 40000,
                         50000, 11200, 3500, 12000, 2750]
})

# ============================
# SOURCE 2 : Infos magasins
# ============================
magasins_info = pd.DataFrame({
    'magasin': ['Paris', 'Lyon', 'Marseille', 'Bordeaux'],
    'region': ['Ile-de-France', 'Auvergne-Rhône-Alpes', 'PACA', 'Nouvelle-Aquitaine'],
    'surface_m2': [500, 350, 400, 300],
    'nb_employes': [25, 18, 20, 15]
})

# ============================
# SOURCE 3 : Infos produits
# ============================
produits_info = pd.DataFrame({
    'produit': ['Laptop', 'Smartphone', 'Tablette', 'Casque', 'Enceinte'],
    'categorie': ['Informatique', 'Téléphonie', 'Informatique', 'Audio', 'Audio'],
    'prix_unitaire': [1000, 500, 400, 50, 150],
    'fournisseur': ['TechCorp', 'MobilePlus', 'TechCorp', 'SoundMax', 'SoundMax']
})

# ============================
# SOURCE 4 : Objectifs par magasin/trimestre
# ============================
objectifs = pd.DataFrame({
    'magasin': ['Paris', 'Paris', 'Lyon', 'Lyon', 'Marseille', 'Marseille'],
    'trimestre': ['Q1', 'Q2', 'Q1', 'Q2', 'Q1', 'Q2'],
    'objectif_ca': [130000, 140000, 100000, 110000, 110000, 120000]
})

# ============================
# SOURCE 5 : Retours clients
# ============================
retours = pd.DataFrame({
    'produit': ['Laptop', 'Smartphone', 'Casque', 'Laptop', 'Tablette', 'Smartphone'],
    'magasin': ['Paris', 'Lyon', 'Paris', 'Marseille', 'Lyon', 'Paris'],
    'trimestre': ['Q1', 'Q1', 'Q2', 'Q2', 'Q1', 'Q2'],
    'nb_retours': [3, 5, 8, 2, 1, 7]
})

print("✅ Données créées avec succès !")

✅ Données créées avec succès !

##### Exercice A1 : Concatèner les ventes Q1 et Q2

In [19]:
ventes_all = pd.concat([ventes_q1, ventes_q2], keys=['Q1', 'Q2'])
print(ventes_all)
print(ventes_all.index)

         produit    magasin  quantite  chiffre_affaires
Q1 0      Laptop      Paris        45             45000
   1  Smartphone      Paris       120             60000
   2    Tablette      Paris        30             12000
   3      Casque      Paris        80              4000
   4      Laptop       Lyon        35             35000
   5  Smartphone       Lyon        95             47500
   6    Tablette       Lyon        25             10000
   7      Casque       Lyon        60              3000
   8      Laptop  Marseille        50             50000
   9  Smartphone  Marseille       110             55000
Q2 0      Laptop      Paris        50             50000
   1  Smartphone      Paris       130             65000
   2    Tablette      Paris        35             14000
   3      Casque      Paris        90              4500
   4      Laptop       Lyon        40             40000
   5  Smartphone       Lyon       100             50000
   6    Tablette       Lyon        28             11200
   7      Casque       Lyon        70              3500
   8    Tablette  Marseille        30             12000
   9      Casque  Marseille        55              2750
MultiIndex([('Q1', 0),
            ('Q1', 1),
            ('Q1', 2),
            ('Q1', 3),
            ('Q1', 4),
            ('Q1', 5),
            ('Q1', 6),
            ('Q1', 7),
            ('Q1', 8),
            ('Q1', 9),
            ('Q2', 0),
            ('Q2', 1),
            ('Q2', 2),
            ('Q2', 3),
            ('Q2', 4),
            ('Q2', 5),
            ('Q2', 6),
            ('Q2', 7),
            ('Q2', 8),
            ('Q2', 9)],
           )

##### Exercice A2 : Explorer le MultiIndex

a) affichage de toutes les ventes du Q1

In [20]:
ventes_all.loc['Q1']

      produit    magasin  quantite  chiffre_affaires
0      Laptop      Paris        45             45000
1  Smartphone      Paris       120             60000
2    Tablette      Paris        30             12000
3      Casque      Paris        80              4000
4      Laptop       Lyon        35             35000
5  Smartphone       Lyon        95             47500
6    Tablette       Lyon        25             10000
7      Casque       Lyon        60              3000
8      Laptop  Marseille        50             50000
9  Smartphone  Marseille       110             55000

b ) afficher la vente à l'index (Q2, 3), trimestre Q2, ligne 3

In [21]:
ventes_all.loc[('Q2', 3)]
#utilisation d'un tuple pour mieux cibler

produit             Casque
magasin              Paris
quantite                90
chiffre_affaires      4500
Name: (Q2, 3), dtype: object

c ) Utilisation de swaplevel() puis .sort_index() pour inverser les niveaux

In [22]:
ventes_swapped = ventes_all.swaplevel()

In [23]:
ventes_swapped

         produit    magasin  quantite  chiffre_affaires
0 Q1      Laptop      Paris        45             45000
1 Q1  Smartphone      Paris       120             60000
2 Q1    Tablette      Paris        30             12000
3 Q1      Casque      Paris        80              4000
4 Q1      Laptop       Lyon        35             35000
5 Q1  Smartphone       Lyon        95             47500
6 Q1    Tablette       Lyon        25             10000
7 Q1      Casque       Lyon        60              3000
8 Q1      Laptop  Marseille        50             50000
9 Q1  Smartphone  Marseille       110             55000
0 Q2      Laptop      Paris        50             50000
1 Q2  Smartphone      Paris       130             65000
2 Q2    Tablette      Paris        35             14000
3 Q2      Casque      Paris        90              4500
4 Q2      Laptop       Lyon        40             40000
5 Q2  Smartphone       Lyon       100             50000
6 Q2    Tablette       Lyon        28             11200
7 Q2      Casque       Lyon        70              3500
8 Q2    Tablette  Marseille        30             12000
9 Q2      Casque  Marseille        55              2750

In [24]:
ventes_sorted = ventes_swapped.sort_index()

In [25]:
ventes_sorted

         produit    magasin  quantite  chiffre_affaires
0 Q1      Laptop      Paris        45             45000
  Q2      Laptop      Paris        50             50000
1 Q1  Smartphone      Paris       120             60000
  Q2  Smartphone      Paris       130             65000
2 Q1    Tablette      Paris        30             12000
  Q2    Tablette      Paris        35             14000
3 Q1      Casque      Paris        80              4000
  Q2      Casque      Paris        90              4500
4 Q1      Laptop       Lyon        35             35000
  Q2      Laptop       Lyon        40             40000
5 Q1  Smartphone       Lyon        95             47500
  Q2  Smartphone       Lyon       100             50000
6 Q1    Tablette       Lyon        25             10000
  Q2    Tablette       Lyon        28             11200
7 Q1      Casque       Lyon        60              3000
  Q2      Casque       Lyon        70              3500
8 Q1      Laptop  Marseille        50             50000
  Q2    Tablette  Marseille        30             12000
9 Q1  Smartphone  Marseille       110             55000
  Q2      Casque  Marseille        55              2750

Exercice A3 : Creation d'un MultiIndex personnalisé

In [28]:
ventes_indexed = ventes_all.set_index(['magasin', 'produit'])

In [29]:
ventes_indexed

                      quantite  chiffre_affaires
magasin   produit
Paris     Laptop            45             45000
          Smartphone       120             60000
          Tablette          30             12000
          Casque            80              4000
Lyon      Laptop            35             35000
          Smartphone        95             47500
          Tablette          25             10000
          Casque            60              3000
Marseille Laptop            50             50000
          Smartphone       110             55000
Paris     Laptop            50             50000
          Smartphone       130             65000
          Tablette          35             14000
          Casque            90              4500
Lyon      Laptop            40             40000
          Smartphone       100             50000
          Tablette          28             11200
          Casque            70              3500
Marseille Tablette          30             12000
          Casque            55              2750

- a) Sélectionne toutes les ventes du magasin 'Paris'
- b) Sélectionne les ventes de ('Lyon', 'Laptop')
- c) Utilise .unstack() sur le niveau 'produit' pour pivoter le DataFrame
- d) Utilise .stack() pour revenir à la forme initiale

In [30]:
ventes_indexed.loc['Paris']

            quantite  chiffre_affaires
produit
Laptop            45             45000
Smartphone       120             60000
Tablette          30             12000
Casque            80              4000
Laptop            50             50000
Smartphone       130             65000
Tablette          35             14000
Casque            90              4500

In [38]:
ventes_indexed.loc[('Lyon', 'Laptop')]

                 quantite  chiffre_affaires
magasin produit
Lyon    Laptop         35             35000
        Laptop         40             40000

avant d'utiliser unstack on doit gerer les doublons

In [41]:
#On regroupe les doublons en faisant la somme Q1 + Q2

ventes_grouped = ventes_indexed.groupby(level=['magasin', 'produit']).sum()
ventes_grouped['quantite'].unstack('produit')

produit    Casque  Laptop  Smartphone  Tablette
magasin
Lyon          130      75         195        53
Marseille      55      50         110        30
Paris         170      95         250        65

In [43]:
# utilisation de stack() : prendre des colonnes et les remet en lignes dans l'index
ventes_grouped.stack()

magasin    produit
Lyon       Casque      quantite               130
                       chiffre_affaires      6500
           Laptop      quantite                75
                       chiffre_affaires     75000
           Smartphone  quantite               195
                       chiffre_affaires     97500
           Tablette    quantite                53
                       chiffre_affaires     21200
Marseille  Casque      quantite                55
                       chiffre_affaires      2750
           Laptop      quantite                50
                       chiffre_affaires     50000
           Smartphone  quantite               110
                       chiffre_affaires     55000
           Tablette    quantite                30
                       chiffre_affaires     12000
Paris      Casque      quantite               170
                       chiffre_affaires      8500
           Laptop      quantite                95
                       chiffre_affaires     95000
           Smartphone  quantite               250
                       chiffre_affaires    125000
           Tablette    quantite                65
                       chiffre_affaires     26000
dtype: int64